/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./components/Base.vue')['default']
    ConverterResetDialog: typeof import('./components/ConverterResetDialog.vue')['default']
    Converters: typeof import('./components/Converters.vue')['default']
    CTFWizardDialog: typeof import('./components/CTFWizardDialog.vue')['default']
    ErrorBanner: typeof import('./components/ErrorBanner.vue')['default']
    Graph: typeof import('./components/Graph.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PcapOverIP: typeof import('./components/PcapOverIP.vue')['default']
    Pcaps: typeof import('./components/Pcaps.vue')['default']
    Results: typeof import('./components/Results.vue')['default']
    ResultsLayout: typeof import('./components/ResultsLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    Status: typeof import('./components/Status.vue')['default']
    Stream: typeof import('./components/Stream.vue')['default']
    StreamData: typeof import('./components/StreamData.vue')['default']
    TagColorChangeDialog: typeof import('./components/TagColorChangeDialog.vue')['default']
    TagCreateDialog: typeof import('./components/TagCreateDialog.vue')['default']
    TagDefinitionChangeDialog: typeof import('./components/TagDefinitionChangeDialog.vue')['default']
    TagDeleteDialog: typeof import('./components/TagDeleteDialog.vue')['default']
    TagDetailsDialog: typeof import('./components/TagDetailsDialog.vue')['default']
    TagNameChangeDialog: typeof import('./components/TagNameChangeDialog.vue')['default']
    Tags: typeof import('./components/Tags.vue')['default']
    TagSetConverterDialog: typeof import('./components/TagSetConverterDialog.vue')['default']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    Webhooks: typeof import('./components/Webhooks.vue')['default']
  }
}
