/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Base: typeof import('./src/components/Base.vue')['default']
    ConverterResetDialog: typeof import('./src/components/ConverterResetDialog.vue')['default']
    Converters: typeof import('./src/components/Converters.vue')['default']
    CTFWizardDialog: typeof import('./src/components/CTFWizardDialog.vue')['default']
    ErrorBanner: typeof import('./src/components/ErrorBanner.vue')['default']
    Graph: typeof import('./src/components/Graph.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PcapOverIP: typeof import('./src/components/PcapOverIP.vue')['default']
    Pcaps: typeof import('./src/components/Pcaps.vue')['default']
    Results: typeof import('./src/components/Results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    Status: typeof import('./src/components/Status.vue')['default']
    Stream: typeof import('./src/components/Stream.vue')['default']
    StreamData: typeof import('./src/components/StreamData.vue')['default']
    TagColorChangeDialog: typeof import('./src/components/TagColorChangeDialog.vue')['default']
    TagCreateDialog: typeof import('./src/components/TagCreateDialog.vue')['default']
    TagDefinitionChangeDialog: typeof import('./src/components/TagDefinitionChangeDialog.vue')['default']
    TagDeleteDialog: typeof import('./src/components/TagDeleteDialog.vue')['default']
    TagDetailsDialog: typeof import('./src/components/TagDetailsDialog.vue')['default']
    TagNameChangeDialog: typeof import('./src/components/TagNameChangeDialog.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    TagSetConverterDialog: typeof import('./src/components/TagSetConverterDialog.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
